version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: lending_postgres
    environment:
      POSTGRES_DB: lending_db
      POSTGRES_USER: lending_user
      POSTGRES_PASSWORD: lending_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lending_user -d lending_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7.0
    container_name: lending_mongodb
    environment:
      MONGO_INITDB_DATABASE: lending_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongo_data:
